services:

  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Consola web
    volumes:
      - ./minio/data:/data
    command: ["server", "/data", "--console-address", "9001:9001"]

  mlflow:
    build:
      dockerfile: docker/Dockerfile-mlflow
      context: .
    container_name: mlflow-server
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./mlflow:/mlruns
    ports:
      - "5000:5000" # MLflow UI
    depends_on:
      - minio
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlruns/mlruns.db", "--serve-artifacts","--default-artifact-root", "s3://mlflow-artifacts", "--artifacts-destination", "s3://mlflow-artifacts"]

  prefect:
    image: prefecthq/prefect:3.4.9-python3.12
    container_name: prefect-server
    ports:
      - "4200:4200" # Prefect UI and API
    volumes:
      - ./prefect:/root/.prefect
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////root/.prefect/prefect.db
      - PREFECT_SERVER_UI_ENABLED=true
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED=false
    command: ["prefect", "server", "start"]
    profiles: ["dev-cpu", "dev-gpu"]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  ml-prod-env-cpu:
    extends:
      file: docker/templates.yml
      service: ml-env
    image: ghcr.io/facug91/ml-prod-env-cpu:latest
    container_name: ml-prod-env-cpu
    volumes:
      - ./workspace/web-service:/root/workspace
      - ./.bash_history:/root/.bash_history
    working_dir: /root/workspace
    environment:
      - WEB_SERVICE_URL=http://localhost:8080
      - FLASK_ENV=production
      - FLASK_APP=app.py
    depends_on:
      - minio
      - mlflow
      - postgres
    profiles: ["prod-cpu"]
    command: "/opt/venv/bin/python3 -m gunicorn --bind 0.0.0.0:8080 app:app"

  ml-dev-env-cpu:
    extends:
      file: docker/templates.yml
      service: ml-env
    image: ghcr.io/facug91/ml-dev-env-cpu:latest
    container_name: ml-dev-env-cpu
    volumes:
      - ./workspace:/root/workspace
      - ./.bash_history:/root/.bash_history
    working_dir: /root/workspace
    depends_on:
      - minio
      - mlflow
      - prefect
      - postgres
    profiles: ["dev-cpu"]

  ml-prod-env-gpu:
    extends:
      file: docker/templates.yml
      service: ml-env
    image: ghcr.io/facug91/ml-prod-env-gpu:latest
    container_name: ml-prod-env-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./workspace/web-service:/root/workspace
      - ./.bash_history:/root/.bash_history
    working_dir: /root/workspace
    environment:
      - WEB_SERVICE_URL=http://localhost:8080
      - FLASK_ENV=production
      - FLASK_APP=app.py
    depends_on:
      - minio
      - mlflow
      - postgres
    profiles: ["prod-gpu"]
    command: "/opt/venv/bin/python3 -m gunicorn --bind 0.0.0.0:8080 app:app"

  ml-dev-env-gpu:
    extends:
      file: docker/templates.yml
      service: ml-env
    image: ghcr.io/facug91/ml-dev-env-gpu:latest
    container_name: ml-dev-env-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./workspace:/root/workspace
      - ./.bash_history:/root/.bash_history
    working_dir: /root/workspace
    depends_on:
      - minio
      - mlflow
      - prefect
      - postgres
    profiles: ["dev-gpu"]
