services:

  ml-env:
    shm_size: '10gb'
    ports:
      - "8080:8080"    # Web Service
    restart: unless-stopped
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./workspace:/root/workspace
      - ./.bash_history:/root/.bash_history
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_DEFAULT_REGION=us-east-1
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - TORCH_HOME=/root/workspace/torchvision/cache # torchvision cache folder for pre-trained models
      - PREFECT_API_URL=http://prefect:4200/api
