services:

  ml-env:
    shm_size: '10gb'
    restart: unless-stopped
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_DEFAULT_REGION=us-east-1
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - TORCH_HOME=/root/workspace/torchvision/cache # Torchvision cache folder for pre-trained models
      - PREFECT_API_URL=http://prefect:4200/api
      - MLFLOW_URL=http://mlflow:5000
      - MODEL_LOCATION=/root/workspace/models/mobilenet_v3_small_weights.pth
      - MODEL_MLFLOW_URI="models:/MNISTClassifier/Production" # Only used if MODEL_LOCATION is not set
      - MLFLOW_EXPERIMENT=fruits-classifier
